# Generated by Django 2.1.5 on 2021-06-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='does_richard_like_lolis',
            field=models.BooleanField(default=True),
        ),
    ]
