# Generated by Django 2.1.5 on 2021-06-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testapp_does_richard_like_lolis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testapp',
            old_name='does_richard_like_lolis',
            new_name='Does_Richard_like_lolis',
        ),
    ]
