# Generated by Django 2.1.5 on 2021-06-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210625_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapp',
            name='otherstuff',
        ),
        migrations.AddField(
            model_name='testapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12345.67, max_digits=7),
        ),
    ]
