# Generated by Django 2.1.5 on 2021-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210628_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='desc2',
            field=models.TextField(default='filler text'),
        ),
    ]
